// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	graph "github.com/startdusk/twitter/cmd/twitter/graph"
	mock "github.com/stretchr/testify/mock"
)

// QueryResolver is an autogenerated mock type for the QueryResolver type
type QueryResolver struct {
	mock.Mock
}

// Me provides a mock function with given fields: ctx
func (_m *QueryResolver) Me(ctx context.Context) (*graph.User, error) {
	ret := _m.Called(ctx)

	var r0 *graph.User
	if rf, ok := ret.Get(0).(func(context.Context) *graph.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*graph.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Tweets provides a mock function with given fields: ctx
func (_m *QueryResolver) Tweets(ctx context.Context) ([]*graph.Tweet, error) {
	ret := _m.Called(ctx)

	var r0 []*graph.Tweet
	if rf, ok := ret.Get(0).(func(context.Context) []*graph.Tweet); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*graph.Tweet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewQueryResolver interface {
	mock.TestingT
	Cleanup(func())
}

// NewQueryResolver creates a new instance of QueryResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewQueryResolver(t mockConstructorTestingTNewQueryResolver) *QueryResolver {
	mock := &QueryResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
