// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	data "github.com/startdusk/twitter/data"
	mock "github.com/stretchr/testify/mock"
)

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, user
func (_m *UserRepo) Create(ctx context.Context, user data.User) (data.User, error) {
	ret := _m.Called(ctx, user)

	var r0 data.User
	if rf, ok := ret.Get(0).(func(context.Context, data.User) data.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(data.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, data.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepo) GetByEmail(ctx context.Context, email string) (data.User, error) {
	ret := _m.Called(ctx, email)

	var r0 data.User
	if rf, ok := ret.Get(0).(func(context.Context, string) data.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(data.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUsername provides a mock function with given fields: ctx, username
func (_m *UserRepo) GetByUsername(ctx context.Context, username string) (data.User, error) {
	ret := _m.Called(ctx, username)

	var r0 data.User
	if rf, ok := ret.Get(0).(func(context.Context, string) data.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(data.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUserRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserRepo(t mockConstructorTestingTNewUserRepo) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
